# Configuration file for the application
server:
    port: 8080
logging:
    level:
        io.mindsync: DEBUG
        org.springframework.security: DEBUG
spring:
    application:
        name: ${application.name}
    main:
        allow-bean-definition-overriding: true
    profiles:
        active: dev
    security:
        oauth2:
            client:
                registration:
                    oidc:
                        client-secret: ${application.security.oauth2.client-secret}
                        client-id: ${application.security.oauth2.client-id}
                        scope: openid,profile,email
                provider:
                    oidc:
                        issuer-uri: ${application.security.oauth2.issuer-uri}
    neo4j:
        uri: bolt://localhost:7687
        authentication:
            username: ${NEO4J_USERNAME:neo4j}
            password: ${NEO4J_PASSWORD:margin-saturn-presto-saga-slogan-8117}

application:
    name: mindsync
    description: MindSync is the take note of the future. It's a note taking app that uses AI to help you take notes.
    version: 0.0.1-SNAPSHOT
    security:
        oauth2:
            base-url: ${OAUTH2_SERVER_URL:http://localhost:7080}
            server-url: ${application.security.oauth2.base-url}
            issuer-uri: ${application.security.oauth2.base-url}/realms/${application.security.oauth2.realm}
            realm: ${REALM:mindsync}
            client-id: ${CLIENT_ID:web_app}
            client-secret: ${CLIENT_SECRET:web_app}
            admin-client-id: ${ADMIN_CLIENT_ID:admin-cli}
            admin-realm: ${ADMIN_REALM:master}
            admin-username: ${ADMIN_USERNAME:admin}
            admin-password: ${ADMIN_PASSWORD:secret}
            audience:
                - account
                - api://default

management:
    endpoints:
        web:
            exposure:
                include: info, health, beans, openapi, swagger-ui
# swagger-ui custom path
springdoc:
    show-actuator: true
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
        path: /api-docs
        csrf:
            enabled: true
