# Configuration file for the application
server:
    port: 8080
logging:
    level:
        io.mindsync: DEBUG
        org.springframework.security: DEBUG
spring:
    application:
        name: mindsync
    profiles:
        active: dev
    security:
        oauth2:
            client:
                registration:
                    oidc:
                        client-secret: web_app
                        client-id: web_app
                        scope: openid,profile,email
                provider:
                    oidc:
                        issuer-uri: http://localhost:7080/realms/mindsync
    neo4j:
        uri: bolt://localhost:7687
        authentication:
            username: neo4j
            password: margin-saturn-presto-saga-slogan-8117

application:
    security:
        oauth2:
            audience:
                - account
                - api://default

management:
    endpoints:
        web:
            exposure:
                include: info, health, beans
