name: Code Quality Checks

on:
    pull_request:
        branches:
            - main
            - develop
    push:
        branches:
            - main
            - develop

jobs:
    build:
        strategy:
            matrix:
                os: [ ubuntu-latest ]
        runs-on: ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-java@v3
                with:
                    distribution: corretto
                    java-version: 17
            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2

            -   name: Run Tests
                run: ./gradlew test

            -   name: Run Test Coverage
                run: ./gradlew check codeCoverageReport

            -   name: Generate JaCoCo Badge
                uses: cicirello/jacoco-badge-generator@v2
                with:
                    generate-branches-badge: true
                    jacoco-csv-file: build/reports/jacoco/codeCoverageReport/codeCoverageReport.csv

            -   name: Log coverage percentage
                run: |
                    echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
                    echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

            -   name: Commit and push the badge (if it changed)
                uses: EndBug/add-and-commit@v7
                with:
                    default_author: github_actions
                    message: 'commit badge'
                    add: '*.svg'

            -   name: Upload JaCoCo coverage report
                uses: actions/upload-artifact@v3
                with:
                    name: jacoco-report
                    path: target/site/jacoco/
