name: Run Gradle on PRs

on:
    pull_request:
        branches:
            - main
            - develop
    push:
        branches:
            - main
            - develop

jobs:
    build:
        strategy:
            matrix:
                os: [ ubuntu-latest, macos-latest, windows-latest ]
        runs-on: ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-java@v3
                with:
                    distribution: corretto
                    java-version: 17
            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2
            -   name: Run build --scan with Gradle wrapper
                id: gradle
                env:
                    BUILD_SCAN_TOS_ACCEPTED: true
                run: ./gradlew build --scan
            -   name: "Add build scan URL as PR comment"
                uses: actions/github-script@v6
                if: github.event_name == 'pull_request' && failure()
                with:
                    github-token: ${{secrets.GITHUB_TOKEN}}
                    script: |
                        github.rest.issues.createComment({
                          issue_number: context.issue.number,
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          body: '❌ ${{ github.workflow }} failed: ${{ steps.gradle.outputs.build-scan-url }}'

            -   name: Run Tests
                run: ./gradlew test

            -   name: Run Test Coverage
                run: ./gradlew jacocoTestReport

            -   name: Generate JaCoCo Badge
                uses: cicirello/jacoco-badge-generator@v2
                with:
                    generate-branches-badge: true
                    jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv

            -   name: Log coverage percentage
                run: |
                    echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
                    echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

            -   name: Commit the badge (if it changed)
                run: |
                    if [[ `git status --porcelain` ]]; then
                      git config --global user.name 'Yuniel Acosta'
                      git config --global user.email 'yacosta738@users.noreply.github.com'
                      git add -A
                      git commit -m "Autogenerated JaCoCo coverage badge"
                      git push
                    fi

            -   name: Upload JaCoCo coverage report
                uses: actions/upload-artifact@v3
                with:
                    name: jacoco-report
                    path: target/site/jacoco/
